Repository recoraddic/recoraddic-android, pull requests merged in 2024-06, with the labels that each got.

#21 [feat] 세 번째 페이지 Hive 기능 추가 및 수정
  lib/second_page/second_page.dart
  lib/third_page/goal_layout.dart
  lib/third_page/record_layout.dart
  lib/third_page/third_page.dart
  lib/third_page/third_page_style.dart
Labels: feat

#23 [fix] 3번 페이지 버그 수정
  lib/third_page/third_page.dart
Labels: fix

#25 [fix] 두 번째 페이지 오류 수정
  lib/second_page/second_page.dart
  lib/second_page/widget.dart
Labels: fix

#27 [fix] 3번 페이지 수정
  lib/first_page/first_page.dart
  lib/first_page/questThumbnail.dart
  lib/style/style.dart
  lib/third_page/goal_layout.dart
  lib/third_page/record_layout.dart
  lib/third_page/third_page.dart
Labels: fix

#29 [design] 레이아웃 수정
  lib/first_page/first_page.dart
  lib/second_page/second_page.dart
  lib/second_page/style.dart
  lib/second_page/widget.dart
Labels: design

#35 [design] 목표 "추가" 버튼 사이즈 조정
  lib/third_page/goal_layout.dart
Labels: design

#37 [design] 추가 버튼 각 수정
  lib/style/style.dart
  lib/third_page/goal_layout.dart
Labels: design

#39 [design] 첫번째뷰 달력 날짜 위치 수정
  lib/first_page/first_page.dart
Labels: design
