Repository recoraddic/recoraddic-android, pull requests merged in 2024-05, with the labels that each got.

#11 [chore] 빌드 파일 수정 및 추가
  analysis_options.yaml
  lib/fourth_page/fourth_page.dart
  lib/main.dart
  lib/third_page/goal_layout.dart
  lib/third_page/popup_menu.dart
  lib/third_page/record_block.dart
  lib/third_page/record_layout.dart
  lib/third_page/third_layout.dart
Labels: chore

#13 [rename] 세 번째 페이지 파일 및 types 수정
  .metadata
  lib/main.dart
  lib/second_page/widget.dart
  lib/third_page/goal_layout.dart
  lib/third_page/popup_menu.dart
  lib/third_page/record_block.dart
  lib/third_page/record_layout.dart
  lib/third_page/third_page.dart
  lib/types/goal.dart
  lib/types/goal.g.dart
  lib/types/record.dart
  lib/types/record.g.dart
  lib/types/section_record.dart
  lib/types/section_record.g.dart
  lib/types/third_page_content.dart
  pubspec.lock
  pubspec.yaml
Labels: rename

#15 [feat] connect Hive DB on FirstPage
  android/app/build.gradle
  lib/first_page/first_page.dart
  lib/second_page/second_page.dart
  lib/second_page/widget.dart
  lib/third_page/record_layout.dart
  lib/types/accumulated_quest.dart
  lib/types/accumulated_quest.g.dart
  lib/types/quest.dart
  lib/types/quest.g.dart
Labels: feat

#17 [feat] 세 번째 페이지 Hive 연결
  lib/main.dart
  lib/third_page/goal_layout.dart
  lib/third_page/record_layout.dart
  lib/third_page/third_page.dart
  lib/types/section.dart
  lib/types/section.g.dart
  lib/types/section_record.dart
Labels: feat

#19 [feat] add rest of necessary functionalities on FirstPage
  lib/first_page/first_page.dart
  lib/second_page/second_page.dart
  lib/second_page/widget.dart
  lib/types/accumulated_quest.dart
Labels: feat
